Use the following code for the questions below:

In [5]:
import numpy as np

In [314]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [ ]:
How many negative numbers are there?

In [53]:
neg_no = a[a < 0]

In [315]:
len(neg_no)

4

How many positive numbers are there?

In [55]:
pos_no = a[a > 0]

In [56]:
len(pos_no)

5

How many even positive numbers are there?

In [58]:

pos_no = a[a > 0]

even_pos_no = pos_no[pos_no % 2 == 0]

len(even_pos_no)

3

If you were to add 3 to each data point, how many positive numbers would there be?

In [68]:
b = a + 3
pos_no2 = b[b>0]
len(pos_no2)

10

If you squared each number, what would the new mean and standard deviation be?

In [82]:
c = a ** 2
c_std = c.std()
c_mean = c.mean()
c_std, c_mean

(144.0243035046516, 74.0)

A common statistical operation on a dataset is centering. 

This means to adjust the data such that the mean of the data is 0.

This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [95]:
a_mean = int(a.mean())
d = a - a_mean
d.mean()

0.0

Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x - μ) / σ

In [100]:
z = (a - a_mean) / a_std
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# Setup 1

Use python's built in functionality/operators to determine the following:

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [258]:
a_sum = sum(a)
a_sum

55

In [306]:
a =  np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sum_of_a = a.sum() 
sum_of_a

55

 Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [254]:
min(a)

1

In [112]:
min_of_a = a.min()
min_of_a

1

 Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [255]:
max(a)

10

In [114]:
max_of_a = a.max()
max_of_a

10

 Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [261]:
a_mean = a_sum / len(a)
a_mean

5.5

In [120]:
mean_of_a = a.mean()
mean_of_a

5.5

Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [268]:
a[0]*a[1]*a[2]*a[3]*a[4]*a[5]*a[6]*a[7]*a[8]*a[9]

3628800

In [125]:
product_of_a = a.prod()
product_of_a

3628800

Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [269]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [272]:
(a[0]**2), a[1]**2, a[2]**2, a[3]**2, a[4]**2, a[5]**2, a[6]**2, a[7]**2, a[8]**2, a[9]**2

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)

In [129]:
squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Make a variable named odds_in_a. It should hold only the odd numbers

In [311]:
def find_odd(num):
    a_odd = []
    for number in num:
        if number % 2 != 0:
            a_odd.append(number)
    return a_odd
a_odd = find_odd(a)
print(a_odd)

[1, 3, 5, 7, 9]


In [307]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

Make a variable named evens_in_a. It should hold only the evens.

In [309]:
def find_even(num):
    a_even = []
    for number in num:
        if number % 2 == 0:
            a_even.append(number)
    return a_even
a_even = find_even(a)
print(a_even)

[2, 4, 6, 8, 10]


In [133]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

# Setup 2: 

#What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [
    [3, 4, 5],
    
    [6, 7, 8]
]

 Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
 
sum_of_b = 0

for row in b:

    sum_of_b += sum(row)

In [168]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])
sum_of_b = b.sum()
sum_of_b

33

Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0])

if min(b[0]) <= min(b[1]) 

else min(b[1])

In [169]:
min_of_b = b.min()
min_of_b

3

Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0])

if max(b[0]) >= max(b[1])

else max(b[1])

In [158]:
max_of_b = b.max()
max_of_b

8

Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = 

(sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [161]:
mean_of_b = b.mean()
mean_of_b

5.5

 Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
 
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

In [164]:
product_of_b = b.prod()
product_of_b

20160

 Exercise 6 - refactor the following to use numpy to find the list of squares 
 
squares_of_b = []

for row in b:

    for number in row:
    
        squares_of_b.append(number**2)
        
squares_of_b

In [167]:
squares_of_b = b**2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = []

for row in b:
    
    for number in row:
        
        if(number % 2 != 0):
            
            odds_in_b.append(number)

In [171]:
odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = []

for row in b:

    for number in row:
    
        if(number % 2 == 0):
        
            evens_in_b.append(number)
            
evens_in_b

In [174]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

In [175]:
b

array([[3, 4, 5],
       [6, 7, 8]])

Exercise 10 - transpose the array b.

In [196]:
b_trans = b.transpose()
b_trans

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [182]:
sin_lst = b.ravel()
sin_lst

array([3, 4, 5, 6, 7, 8])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [184]:
six_lst = np.reshape(b, (6, -1))
six_lst

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Setup 3

c = [
    
    [1, 2, 3],
    
    [4, 5, 6],
    
    [7, 8, 9]
    
]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [187]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 1 - Find the min, max, sum, and product of c.

In [191]:
c_min = c.min()
c_max = c.max()
c_sum = c.sum()
c_prod = c.prod()
c_min, c_max, c_sum, c_prod

(1, 9, 45, 362880)

Exercise 2 - Determine the standard deviation of c.

In [192]:
c_std = c.std()
c_std

2.581988897471611

Exercise 3 - Determine the variance of c.

In [194]:
c_var = c.var()
c_var

6.666666666666667

Print out the shape of the array c

In [198]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercise 5 - Transpose c and print out transposed result.

In [200]:
c_trans = c.transpose()
c_trans

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Exercise 6 - Get the dot product of the array c with c. 

In [202]:
c_dot_prod = np.dot(c, c)
c_dot_prod

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [206]:
c_x_c = c * c_trans
cxc_sum = c_x_c.sum()
cxc_sum

261

 Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [208]:
cxc_prod = c_x_c.prod()
cxc_prod

131681894400

# Setup 4

d = [
    
    [90, 30, 45, 0, 120, 180],
    
    [45, -90, -30, 270, 90, 0],
    
    [60, 45, -45, 90, -45, 180]

In [209]:
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

Exercise 1 - Find the sine of all the numbers in d

In [214]:
d_sin = np.sin(d)
d_sin

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 3 - Find the tangent of all the numbers in dFind the tangent of all the numbers in d

In [216]:
d_tan = np.tan(d)
d_tan

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [218]:
d_neg = d[d < 0]
d_neg

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [219]:
d_pos = d[d>0]
d_pos

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d.

In [223]:
d_uniq = np.unique(d)
d_uniq

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d.

In [227]:
d_len = len(d_uniq)
d_len

11

Exercise 8 - Print out the shape of d.

In [226]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

Exercise 9 - Transpose and then print out the shape of d.

In [230]:
d_trans = d.transpose()
d_trans

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

Exercise 10 - Reshape d into an array of 9 x 2

In [240]:
d_rshp = np.reshape(d, (9, 2))
d_rshp

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])